# ns
apiVersion: v1
kind: Namespace
metadata:
  name: webdav-aliyun
# account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webdav-aliyun-sa-clusteradmin
  namespace: webdav-aliyun
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: webdav-aliyun-crb-clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: webdav-aliyun-sa-clusteradmin
    namespace: webdav-aliyun
---
# svc
apiVersion: v1
kind: Service
metadata:
  name: webdav-aliyun
  namespace: webdav-aliyun
spec:
  type: NodePort
  selector:
    app: webdav-aliyun
  ports:
    - name: http
      protocol: TCP
      port: 18080
      targetPort: 8080
      nodePort: 18080
---
# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav-aliyun
  namespace: webdav-aliyun
spec:
  selector:
    matchLabels:
      app: webdav-aliyun
  template:
    metadata:
      labels:
        app: webdav-aliyun
    spec:
      serviceAccountName: webdav-aliyun-sa-clusteradmin
      containers:
        - name: webdav-aliyun
          image: eritpchy/aliyundrive-webdav
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: ALIYUNDRIVE_REFRESH_TOKEN
              value: "xxx"
            - name: ALIYUNDRIVE_AUTH_USER_NAME
              value: "admin"
            - name: ALIYUNDRIVE_AUTH_PASSWORD
              value: "admin"
            - name: JAVA_OPTS
              value: "-Xmx1g"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: aliyun-driver
              mountPath: /conf
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: aliyun-driver
          hostPath:
            path: ./docker/conf